# Install packages
install.packages("readr")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("here")
install.packages("vroom")
install.packages("broom")
install.packages("ordinal")
install.packages("webshot2")
install.packages("modelsummary")
install.packages("here")
install.packages("gridExtra")

# Load packages
library(readr)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(here)
library(vroom)
library(broom)
library(ordinal)
library(webshot2)
library(modelsummary)
library(grid)
library(gridExtra)
