# Install packages
install.packages("readr")
install.packages("tidyverse")
install.packages("dplyr")
install.packages("tidyr")
install.packages("ggplot2")
install.packages("here")
install.packages('lmtest')
install.packages('sandwich')
install.packages('lubridate')
install.packages('broom')
install.packages('writexl')

# Load packages
library(readr)
library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(here)
library(lmtest)
library(sandwich)
library(lubridate)
library(broom)
library(writexl)
